# ─── Theme System ───────────────────────────────────────────
# Multiple themes for the application.
# Each theme defines all colors used across the UI.

THEMES = {
    # ═══════════════════════════════════════════════════════════
    #  1. أزرق فاتح (Blue Light) — الافتراضي
    # ═══════════════════════════════════════════════════════════
    "blue_light": {
        "label": "أزرق فاتح",
        "mode": "light",
        "PRIMARY": "#1a73e8",
        "PRIMARY_HOVER": "#1557b0",
        "BG": "#f0f2f5",
        "SIDEBAR_BG": "#202124",
        "TEXT": "#202124",
        "TEXT_SEC": "#5f6368",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#9ca3af",
        "SECONDARY_HOVER": "#6b7280",
        "CARD_BG": "#ffffff",
        "DIVIDER": "#e5e7eb",
        "ROW_BG": "#f9fafb",
        "DELETE_HOVER": "#fee2e2",
        "SIDEBAR_TEXT": "#e8eaed",
        "SIDEBAR_HOVER": "#3c4043",
        "SIDEBAR_DIVIDER": "#3c4043",
        "SIDEBAR_SUB": "#9aa0a6",
        "ENTRY_BG": "#ffffff",
        "ENTRY_BORDER": "#d1d5db",
        "INFO_BG": "#f0f7ff",
    },

    # ═══════════════════════════════════════════════════════════
    #  2. أزرق داكن (Blue Dark)
    # ═══════════════════════════════════════════════════════════
    "blue_dark": {
        "label": "أزرق داكن",
        "mode": "dark",
        "PRIMARY": "#4d9fff",
        "PRIMARY_HOVER": "#3d8bef",
        "BG": "#0f172a",
        "SIDEBAR_BG": "#020617",
        "TEXT": "#f1f5f9",
        "TEXT_SEC": "#94a3b8",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#64748b",
        "SECONDARY_HOVER": "#475569",
        "CARD_BG": "#1e293b",
        "DIVIDER": "#334155",
        "ROW_BG": "#283548",
        "DELETE_HOVER": "#451a1a",
        "SIDEBAR_TEXT": "#cbd5e1",
        "SIDEBAR_HOVER": "#1e293b",
        "SIDEBAR_DIVIDER": "#1e293b",
        "SIDEBAR_SUB": "#64748b",
        "ENTRY_BG": "#1e293b",
        "ENTRY_BORDER": "#475569",
        "INFO_BG": "#1e3a5f",
    },

    # ═══════════════════════════════════════════════════════════
    #  3. أخضر (Green)
    # ═══════════════════════════════════════════════════════════
    "green": {
        "label": "أخضر",
        "mode": "light",
        "PRIMARY": "#16a34a",
        "PRIMARY_HOVER": "#15803d",
        "BG": "#f0fdf4",
        "SIDEBAR_BG": "#14532d",
        "TEXT": "#14532d",
        "TEXT_SEC": "#4d7c56",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#9ca3af",
        "SECONDARY_HOVER": "#6b7280",
        "CARD_BG": "#ffffff",
        "DIVIDER": "#dcfce7",
        "ROW_BG": "#f0fdf4",
        "DELETE_HOVER": "#fef2f2",
        "SIDEBAR_TEXT": "#dcfce7",
        "SIDEBAR_HOVER": "#166534",
        "SIDEBAR_DIVIDER": "#166534",
        "SIDEBAR_SUB": "#86efac",
        "ENTRY_BG": "#ffffff",
        "ENTRY_BORDER": "#bbf7d0",
        "INFO_BG": "#f0fdf4",
    },

    # ═══════════════════════════════════════════════════════════
    #  4. بنفسجي (Purple)
    # ═══════════════════════════════════════════════════════════
    "purple": {
        "label": "بنفسجي",
        "mode": "light",
        "PRIMARY": "#7c3aed",
        "PRIMARY_HOVER": "#6d28d9",
        "BG": "#faf5ff",
        "SIDEBAR_BG": "#2e1065",
        "TEXT": "#2e1065",
        "TEXT_SEC": "#6b5b95",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#9ca3af",
        "SECONDARY_HOVER": "#6b7280",
        "CARD_BG": "#ffffff",
        "DIVIDER": "#e9d5ff",
        "ROW_BG": "#faf5ff",
        "DELETE_HOVER": "#fef2f2",
        "SIDEBAR_TEXT": "#e9d5ff",
        "SIDEBAR_HOVER": "#4c1d95",
        "SIDEBAR_DIVIDER": "#4c1d95",
        "SIDEBAR_SUB": "#a78bfa",
        "ENTRY_BG": "#ffffff",
        "ENTRY_BORDER": "#d8b4fe",
        "INFO_BG": "#faf5ff",
    },

    # ═══════════════════════════════════════════════════════════
    #  5. برتقالي (Orange)
    # ═══════════════════════════════════════════════════════════
    "orange": {
        "label": "برتقالي",
        "mode": "light",
        "PRIMARY": "#ea580c",
        "PRIMARY_HOVER": "#c2410c",
        "BG": "#fff7ed",
        "SIDEBAR_BG": "#431407",
        "TEXT": "#431407",
        "TEXT_SEC": "#9a6244",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#9ca3af",
        "SECONDARY_HOVER": "#6b7280",
        "CARD_BG": "#ffffff",
        "DIVIDER": "#fed7aa",
        "ROW_BG": "#fff7ed",
        "DELETE_HOVER": "#fef2f2",
        "SIDEBAR_TEXT": "#fed7aa",
        "SIDEBAR_HOVER": "#7c2d12",
        "SIDEBAR_DIVIDER": "#7c2d12",
        "SIDEBAR_SUB": "#fdba74",
        "ENTRY_BG": "#ffffff",
        "ENTRY_BORDER": "#fdba74",
        "INFO_BG": "#fff7ed",
    },

    # ═══════════════════════════════════════════════════════════
    #  6. أحمر (Red)
    # ═══════════════════════════════════════════════════════════
    "red": {
        "label": "أحمر",
        "mode": "dark",
        "PRIMARY": "#f43f5e",
        "PRIMARY_HOVER": "#e11d48",
        "BG": "#1a0a0e",
        "SIDEBAR_BG": "#0f0507",
        "TEXT": "#fda4af",
        "TEXT_SEC": "#a0616f",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#6b4057",
        "SECONDARY_HOVER": "#4f2d3c",
        "CARD_BG": "#2a1218",
        "DIVIDER": "#4c1d26",
        "ROW_BG": "#331520",
        "DELETE_HOVER": "#451a1a",
        "SIDEBAR_TEXT": "#fda4af",
        "SIDEBAR_HOVER": "#2a1218",
        "SIDEBAR_DIVIDER": "#2a1218",
        "SIDEBAR_SUB": "#9f4057",
        "ENTRY_BG": "#2a1218",
        "ENTRY_BORDER": "#6b2035",
        "INFO_BG": "#2a1520",
    },

    # ═══════════════════════════════════════════════════════════
    #  7. سماوي (Cyan / Teal)
    # ═══════════════════════════════════════════════════════════
    "teal": {
        "label": "سماوي",
        "mode": "light",
        "PRIMARY": "#0d9488",
        "PRIMARY_HOVER": "#0f766e",
        "BG": "#f0fdfa",
        "SIDEBAR_BG": "#134e4a",
        "TEXT": "#134e4a",
        "TEXT_SEC": "#4d7c75",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#9ca3af",
        "SECONDARY_HOVER": "#6b7280",
        "CARD_BG": "#ffffff",
        "DIVIDER": "#ccfbf1",
        "ROW_BG": "#f0fdfa",
        "DELETE_HOVER": "#fef2f2",
        "SIDEBAR_TEXT": "#ccfbf1",
        "SIDEBAR_HOVER": "#115e59",
        "SIDEBAR_DIVIDER": "#115e59",
        "SIDEBAR_SUB": "#5eead4",
        "ENTRY_BG": "#ffffff",
        "ENTRY_BORDER": "#99f6e4",
        "INFO_BG": "#f0fdfa",
    },

    # ═══════════════════════════════════════════════════════════
    #  8. رمادي داكن (Slate Dark)
    # ═══════════════════════════════════════════════════════════
    "slate_dark": {
        "label": "رمادي داكن",
        "mode": "dark",
        "PRIMARY": "#38bdf8",
        "PRIMARY_HOVER": "#0ea5e9",
        "BG": "#0f172a",
        "SIDEBAR_BG": "#020617",
        "TEXT": "#e2e8f0",
        "TEXT_SEC": "#94a3b8",
        "SUCCESS": "#22c55e",
        "SUCCESS_HOVER": "#16a34a",
        "DANGER": "#ef4444",
        "DANGER_HOVER": "#dc2626",
        "WARNING": "#f59e0b",
        "WARNING_HOVER": "#d97706",
        "SECONDARY": "#64748b",
        "SECONDARY_HOVER": "#475569",
        "CARD_BG": "#1e293b",
        "DIVIDER": "#334155",
        "ROW_BG": "#283548",
        "DELETE_HOVER": "#451a1a",
        "SIDEBAR_TEXT": "#cbd5e1",
        "SIDEBAR_HOVER": "#1e293b",
        "SIDEBAR_DIVIDER": "#1e293b",
        "SIDEBAR_SUB": "#64748b",
        "ENTRY_BG": "#1e293b",
        "ENTRY_BORDER": "#475569",
        "INFO_BG": "#1e3a5f",
    },
}

# ─── Theme keys list for iteration ───────────────────────────
THEME_ORDER = [
    "blue_light", "blue_dark", "green", "purple",
    "orange", "red", "teal", "slate_dark"
]